### ISSUE TITLE
Add pixel coordinate display on mouse hover and field to enter calibration coordiantes

### ISSUE THREAD

**Issue by SloMusti** [IRNAS/koruza-ui#4]
Add pixel coordinate display on mouse hover and field to enter calibration coordinates. Alternatively we could have a button with function, use current coordinates as the calibration value.

**Comment by kostko** [comment]
> Alternatively we could have a button with function, use current coordinates as the calibration value.

Which ones are the "current" coordinates?

**Comment by SloMusti** [comment]
Current coordinates are the pixel values of where the red square is currently pointing
